In [100]:
import pandas as pd
import numpy as np

sales = pd.read_csv("Europe Sales Records.csv")

sales.head()

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Europe,Czech Republic,Beverages,Offline,C,9/12/2011,478051030,9/29/2011,4778,47.45,31.79,226716.10,151892.62,74823.48
1,Europe,Bosnia and Herzegovina,Clothes,Online,M,10/14/2013,919133651,11/4/2013,927,109.28,35.84,101302.56,33223.68,68078.88
2,Europe,Austria,Cereal,Offline,C,8/13/2014,987410676,9/6/2014,5616,205.70,117.11,1155211.20,657689.76,497521.44
3,Europe,Bulgaria,Office Supplies,Online,L,10/31/2010,672330081,11/29/2010,6266,651.21,524.96,4080481.86,3289399.36,791082.50
4,Europe,Estonia,Fruits,Online,L,9/28/2016,579463422,11/1/2016,4958,9.33,6.92,46258.14,34309.36,11948.78

In [101]:
sales.shape

(1330, 14)

In [102]:
sales.columns

Index(['Region', 'Country', 'Item Type', 'Sales Channel', 'Order Priority',
       'Order Date', 'Order ID', 'Ship Date', 'Units Sold', 'Unit Price',
       'Unit Cost', 'Total Revenue', 'Total Cost', 'Total Profit'],
      dtype='object')

In [103]:
sales.dtypes

Region             object
Country            object
Item Type          object
Sales Channel      object
Order Priority     object
Order Date         object
Order ID            int64
Ship Date          object
Units Sold          int64
Unit Price        float64
Unit Cost         float64
Total Revenue     float64
Total Cost        float64
Total Profit      float64
dtype: object

In [104]:
sales.isnull().sum()

Region            0
Country           0
Item Type         0
Sales Channel     0
Order Priority    0
Order Date        0
Order ID          0
Ship Date         0
Units Sold        0
Unit Price        0
Unit Cost         0
Total Revenue     0
Total Cost        0
Total Profit      0
dtype: int64

In [105]:
sales.duplicated().sum()

np.int64(0)

In [106]:
sales = sales.drop_duplicates()

sales.shape

(1330, 14)

In [107]:
country_revenue = sales.groupby("Country")["Total Revenue"].sum()
country_revenue.sort_values(
    ascending=False
).head(10)

Country
Kosovo                    53833142.79
Czech Republic            53543932.14
Ukraine                   53252317.54
Bosnia and Herzegovina    50117508.49
Macedonia                 49222085.25
San Marino                47883708.48
Andorra                   47756693.17
Portugal                  47172189.84
Malta                     47145320.81
Russia                    46051659.81
Name: Total Revenue, dtype: float64

In [108]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [109]:
country_profit = sales.groupby("Country")["Total Profit"].sum()

country_profit

Country
Albania                   10490706.02
Andorra                   15410036.63
Armenia                    9422353.18
Austria                   10027509.64
Belarus                   11852421.05
Belgium                    7476060.14
Bosnia and Herzegovina    13257602.77
Bulgaria                  10408342.61
Croatia                    7388447.57
Cyprus                    10032220.56
Czech Republic            13635593.78
Denmark                    9617418.06
Estonia                    7828593.56
Finland                    7525362.83
France                    10842345.66
Georgia                    5697679.21
Germany                   11582919.10
Greece                    12324450.13
Hungary                   13786231.03
Iceland                    7278112.15
Ireland                    9830365.71
Italy                     10913921.97
Kosovo                    14409145.45
Latvia                    10759285.29
Liechtenstein              8397411.11
Lithuania                  7997297.83
Luxembourg                 9870766.11
Macedonia                 13684099.95
Malta                     14610127.88
Moldova                    6902456.08
Monaco                     4797048.77
Montenegro                11169660.56
Netherlands                5762490.70
Norway                     9875771.81
Poland                    10671100.99
Portugal                  11345407.59
Romania                   10793548.69
Russia                    13267682.64
San Marino                13792992.81
Serbia                    11853514.38
Slovakia                  12052790.03
Slovenia                  12123524.52
Spain                      8173545.22
Sweden                    11155328.59
Switzerland               11037297.60
Ukraine                   14804925.74
United Kingdom             9326312.21
Vatican City               6413822.41
Name: Total Profit, dtype: float64

In [110]:
country_profit.sort_values(
    ascending=False
).head(5)

Country
Andorra       15410036.63
Ukraine       14804925.74
Malta         14610127.88
Kosovo        14409145.45
San Marino    13792992.81
Name: Total Profit, dtype: float64

In [111]:
country_profit.sort_values().head(5)

Country
Monaco          4797048.77
Georgia         5697679.21
Netherlands     5762490.70
Vatican City    6413822.41
Moldova         6902456.08
Name: Total Profit, dtype: float64

In [112]:
item_units = sales.groupby(
    "Item Type"
)["Units Sold"].sum()

item_units

Item Type
Baby Food          562706
Beverages          613133
Cereal             465685
Clothes            591385
Cosmetics          533291
Fruits             591672
Household          440249
Meat               533376
Office Supplies    617641
Personal Care      560480
Snacks             490160
Vegetables         582544
Name: Units Sold, dtype: int64

In [113]:
item_revenue = sales.groupby(
    "Item Type"
)["Total Revenue"].sum()

item_revenue.idxmax()

'Office Supplies'

In [114]:
item_profit = sales.groupby(
    "Item Type"
)["Total Profit"].sum()

item_profit.idxmax()

'Cosmetics'

In [115]:
channel_revenue = sales.groupby(
    "Sales Channel"
)["Total Revenue"].sum()

channel_revenue

Sales Channel
Offline    8.732536e+08
Online     8.303688e+08
Name: Total Revenue, dtype: float64

In [116]:
channel_profit = sales.groupby(
    "Sales Channel"
)["Total Profit"].sum()

channel_profit

Sales Channel
Offline    2.537081e+08
Online     2.479679e+08
Name: Total Profit, dtype: float64

In [117]:
channel_profit.idxmax()

'Offline'

In [118]:
sales["Order Priority"].value_counts()

Order Priority
M    354
H    335
L    334
C    307
Name: count, dtype: int64

In [119]:
avg_profit = sales.groupby(
    "Order Priority"
)["Total Profit"].mean()

avg_profit

Order Priority
C    395873.863941
H    383001.165672
L    343937.392096
M    386899.131723
Name: Total Profit, dtype: float64

In [120]:
avg_profit.idxmax()

'C'

In [121]:
sales["Total Revenue"].corr(
    sales["Total Profit"]
)

np.float64(0.8739605151424565)

In [122]:
correlation = sales["Total Revenue"].corr(
    sales["Total Profit"]
)

if correlation > 0:
    print("Higher revenue generally leads to higher profit")
else:
    print("No positive relationship")

Higher revenue generally leads to higher profit

In [123]:
sales["Order Date"] = pd.to_datetime(
    sales["Order Date"]
)

In [124]:
sales["Month"] = sales["Order Date"].dt.month_name()

In [125]:
monthly_sales = sales.groupby(
    "Month"
)["Total Revenue"].sum()

monthly_sales

Month
April        1.148074e+08
August       1.172059e+08
December     1.470954e+08
February     1.415449e+08
January      1.579039e+08
July         1.559474e+08
June         1.660835e+08
March        1.706923e+08
May          1.577288e+08
November     1.394554e+08
October      1.078330e+08
September    1.273245e+08
Name: Total Revenue, dtype: float64

In [126]:
monthly_sales.idxmax()

'March'

In [127]:
monthly_sales.idxmin()

'October'

In [128]:
summary = {
    "Total Revenue": sales["Total Revenue"].sum(),
    "Total Profit": sales["Total Profit"].sum(),
    "Best Country": country_revenue.idxmax(),
    "Best Item Type": item_units.idxmax(),
    "Best Sales Channel": channel_profit.idxmax(),
    "Total Orders": sales["Order ID"].count()
}

summary

{'Total Revenue': np.float64(1703622398.11),
 'Total Profit': np.float64(501676048.32000005),
 'Best Country': 'Kosovo',
 'Best Item Type': 'Office Supplies',
 'Best Sales Channel': 'Offline',
 'Total Orders': np.int64(1330)}