In [115]:
import pandas as pd

movies = pd.read_csv("Movie-Assignment-Data-1.csv")

# Shape
print(movies.shape)

# Columns
print(movies.columns)

# Data types
print(movies.dtypes)

# Basic info
movies.info()

# First 5 rows
movies.head()

(5043, 28)
Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')
color                         object
director_name                 object
num_critic_for_reviews       float64
duration                     float64
director_facebook_likes      float64
actor_3_facebook_likes       float64
actor_2_name                  object
actor_1_facebook_likes       float64
gross                        float64
genres                        object
actor_1_name                  object
movie_title                   object
num_voted_users                int64
cast_total_facebook_likes      int64
actor_3_name                  object
facenumber_in_poster         float64
plot_keywords                 object
movie_imdb_link               object
num_user_for_reviews         float64
language                      object
country                       object
content_rating                object
budget                       float64
title_year                   float64
actor_2_facebook_likes       float64
imdb_score                   float64
aspect_ratio                 float64
movie_facebook_likes           int64
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      5024 non-null   object
 1   director_name              4939 non-null   object
 2   num_critic_for_reviews     4993 non-null   float64
 3   duration                   5028 non-null   float64
 4   director_facebook_likes    4939 non-null   float64
 5   actor_3_facebook_likes     5020 non-null   float64
 6   actor_2_name               5030 non-null   object
 7   actor_1_facebook_likes     5036 non-null   float64
 8   gross                      4159 non-null   float64
 9   genres                     5043 non-null   object
 10  actor_1_name               5036 non-null   object
 11  movie_title                5043 non-null   object
 12  num_voted_users            5043 non-null   int64
 13  cast_total_facebook_likes  5043 non-null   int64
 14  actor_3_name               5020 non-null   object
 15  facenumber_in_poster       5030 non-null   float64
 16  plot_keywords              4890 non-null   object
 17  movie_imdb_link            5043 non-null   object
 18  num_user_for_reviews       5022 non-null   float64
 19  language                   5029 non-null   object
 20  country                    5038 non-null   object
 21  content_rating             4740 non-null   object
 22  budget                     4551 non-null   float64
 23  title_year                 4935 non-null   float64
 24  actor_2_facebook_likes     5030 non-null   float64
 25  imdb_score                 5043 non-null   float64
 26  aspect_ratio               4714 non-null   float64
 27  movie_facebook_likes       5043 non-null   int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [116]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [117]:
# Null values in columns
null_col = movies.isnull().sum()
print(null_col)

# Null values in rows
null_row = movies.isnull().sum(axis=1)
print(null_row)

# Percentage null values
null_percent = round((movies.isnull().sum()/len(movies))*100,2)
print(null_percent)

color                         19
director_name                104
num_critic_for_reviews        50
duration                      15
director_facebook_likes      104
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        884
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                153
movie_imdb_link                0
num_user_for_reviews          21
language                      14
country                        5
content_rating               303
budget                       492
title_year                   108
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
dtype: int64
0        0
1        0
2        0
3        0
4       14
        ..
5038     4
5039     5
5040     4
5041     2
5042     0
Length: 5043, dtype: int64
color                         0.38
director_name                 2.06
num_critic_for_reviews        0.99
duration                      0.30
director_facebook_likes       2.06
actor_3_facebook_likes        0.46
actor_2_name                  0.26
actor_1_facebook_likes        0.14
gross                        17.53
genres                        0.00
actor_1_name                  0.14
movie_title                   0.00
num_voted_users               0.00
cast_total_facebook_likes     0.00
actor_3_name                  0.46
facenumber_in_poster          0.26
plot_keywords                 3.03
movie_imdb_link               0.00
num_user_for_reviews          0.42
language                      0.28
country                       0.10
content_rating                6.01
budget                        9.76
title_year                    2.14
actor_2_facebook_likes        0.26
imdb_score                    0.00
aspect_ratio                  6.52
movie_facebook_likes          0.00
dtype: float64

In [118]:
drop_cols = [
    'color',
    'director_facebook_likes',
    'actor_1_facebook_likes',
    'actor_2_facebook_likes',
    'actor_3_facebook_likes',
    'actor_2_name',
    'cast_total_facebook_likes',
    'actor_3_name',
    'duration',
    'facenumber_in_poster',
    'content_rating',
    'country',
    'movie_imdb_link',
    'aspect_ratio',
    'plot_keywords'
]

movies = movies.drop(columns=drop_cols)

In [119]:
# After dropping unnecessary columns
null_percent = round((movies.isnull().sum()/len(movies))*100,2)

high_null_cols = null_percent[null_percent > 5].index

movies = movies.dropna(subset=high_null_cols)

In [143]:
movies = movies[movies.isnull().sum(axis=1) <= 5]

In [140]:
movies['language'].fillna('English', inplace=True)

/tmp/ipykernel_2309/2482251517.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  movies['language'].fillna('English', inplace=True)
/tmp/ipykernel_2309/2482251517.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['language'].fillna('English', inplace=True)

In [129]:
retained_rows = len(movies)

original_rows = pd.read_csv("Movie-Assignment-Data-1.csv").shape[0]

retained_percent = round((retained_rows/original_rows)*100,2)

print("Rows Retained:", retained_rows)
print("Retention %:", retained_percent)

Rows Retained: 3891
Retention %: 77.16

In [133]:
movies['budget'] = movies['budget']/1000000
movies['gross'] = movies['gross']/1000000
movies

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,7.605058e-16,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,2.370000e-16,2009.0,7.9,33000
1,Gore Verbinski,302.0,3.094042e-16,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,3.000000e-16,2007.0,7.1,0
2,Sam Mendes,602.0,2.000742e-16,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,2.450000e-16,2015.0,6.8,85000
3,Christopher Nolan,813.0,4.481306e-16,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,2.500000e-16,2012.0,8.5,164000
5,Andrew Stanton,462.0,7.305868e-17,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,2.637000e-16,2012.0,6.6,24000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5033,Shane Carruth,143.0,4.247600e-19,Drama|Sci-Fi|Thriller,Shane Carruth,Primer,72639,371.0,English,7.000000e-21,2004.0,7.0,19000
5034,Neill Dela Llana,35.0,7.007100e-20,Thriller,Ian Gamazon,Cavite,589,35.0,English,7.000000e-21,2005.0,6.3,74
5035,Robert Rodriguez,56.0,2.040920e-18,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El Mariachi,52055,130.0,Spanish,7.000000e-21,1992.0,6.9,0
5037,Edward Burns,14.0,4.584000e-21,Comedy|Drama,Kerry Bishé,Newlyweds,1338,14.0,English,9.000000e-21,2011.0,6.4,413
5042,Jon Gunn,43.0,8.522200e-20,Documentary,John August,My Date with Drew,4285,84.0,English,1.100000e-21,2004.0,6.6,456

In [144]:
movies['profit'] = movies['gross'] - movies['budget']

top10 = (
    movies.sort_values(by='profit', ascending=False)
          .head(10)
)

top10[['movie_title','profit']]

                                     movie_title        profit
0                                        Avatar   5.235058e-16
29                               Jurassic World   5.021773e-16
26                                      Titanic   4.586723e-16
3024         Star Wars: Episode IV - A New Hope   4.499357e-16
3080                 E.T. the Extra-Terrestrial   4.244495e-16
17                                 The Avengers   4.032795e-16
509                               The Lion King   3.777838e-16
240   Star Wars: Episode I - The Phantom Menace   3.595447e-16
66                              The Dark Knight   3.483161e-16
439                            The Hunger Games   3.299993e-16

In [145]:
movies = movies.drop_duplicates()

movies['profit'] = movies['gross'] - movies['budget']

top10 = (
    movies.sort_values(by='profit', ascending=False)
          .head(10)
)

top10[['movie_title','profit']]

                                     movie_title        profit
0                                        Avatar   5.235058e-16
29                               Jurassic World   5.021773e-16
26                                      Titanic   4.586723e-16
3024         Star Wars: Episode IV - A New Hope   4.499357e-16
3080                 E.T. the Extra-Terrestrial   4.244495e-16
17                                 The Avengers   4.032795e-16
509                               The Lion King   3.777838e-16
240   Star Wars: Episode I - The Phantom Menace   3.595447e-16
66                              The Dark Knight   3.483161e-16
439                            The Hunger Games   3.299993e-16

In [146]:
IMDb_Top_250 = (
    movies[movies['num_voted_users'] > 25000]
    .sort_values(by='imdb_score', ascending=False)
    .head(250)
    .copy()
)

IMDb_Top_250['Rank'] = range(1,251)

IMDb_Top_250.head()

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,Rank
1937,Frank Darabont,199.0,2.834147e-17,Crime|Drama,Morgan Freeman,The Shawshank Redemption,1689764,4144.0,English,2.500000e-17,1994.0,9.3,108000,3.341469e-18,1
3466,Francis Ford Coppola,208.0,1.348220e-16,Crime|Drama,Al Pacino,The Godfather,1155770,2238.0,English,6.000000e-18,1972.0,9.2,43000,1.288220e-16,2
2837,Francis Ford Coppola,149.0,5.730000e-17,Crime|Drama,Robert De Niro,The Godfather: Part II,790926,650.0,English,1.300000e-17,1974.0,9.0,14000,4.430000e-17,3
66,Christopher Nolan,645.0,5.333161e-16,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,1.850000e-16,2008.0,9.0,37000,3.483161e-16,4
4498,Sergio Leone,181.0,6.100000e-18,Western,Clint Eastwood,"The Good, the Bad and the Ugly",503509,780.0,Italian,1.200000e-18,1966.0,8.9,20000,4.900000e-18,5

In [149]:
Top_Foreign_Lang_Film = IMDb_Top_250[
    IMDb_Top_250['language'] != 'English'
]

Top_Foreign_Lang_Film[['movie_title','language']]

                              movie_title    language
4498      The Good, the Bad and the Ugly      Italian
4747                       Seven Samurai     Japanese
4029                         City of God   Portuguese
2373                       Spirited Away     Japanese
4259                 The Lives of Others       German
4921                  Children of Heaven      Persian
1329            Baahubali: The Beginning       Telugu
1298                              Amélie       French
2323                   Princess Mononoke     Japanese
2970                            Das Boot       German
4105                              Oldboy       Korean
4659                        A Separation      Persian
4033                            The Hunt       Danish
2829                            Downfall       German
2734                          Metropolis       German
2047                Howl's Moving Castle     Japanese
2551                     Pan's Labyrinth      Spanish
3550                           Incendies       French
4000            The Secret in Their Eyes      Spanish
3553                         Elite Squad   Portuguese
2914  Tae Guk Gi: The Brotherhood of War       Korean
3423                               Akira     Japanese
4461                     The Celebration       Danish
4267                       Amores Perros      Spanish
2830                      The Sea Inside      Spanish
3344                     My Name Is Khan        Hindi
4144                     Central Station   Portuguese
3456                          Persepolis       French
4284                   Waltz with Bashir       Hebrew
4897                A Fistful of Dollars      Italian
4640        4 Months, 3 Weeks and 2 Days     Romanian
3264                               Amour       French
2863               Letters from Iwo Jima     Japanese
3510                          Veer-Zaara        Hindi
3677                          The Chorus       French
2605      Crouching Tiger, Hidden Dragon     Mandarin
1171                                Hero     Mandarin

In [155]:
top10director = (
    movies.groupby('director_name')['imdb_score']
    .mean()
    .sort_values(ascending=False)
    .head(10)
    .reset_index()
)

top10director

       director_name  imdb_score
0          Tony Kaye    8.600000
1    Charles Chaplin    8.600000
2         Ron Fricke    8.500000
3   Alfred Hitchcock    8.500000
4       Majid Majidi    8.500000
5    Damien Chazelle    8.500000
6       Sergio Leone    8.433333
7  Christopher Nolan    8.425000
8   Richard Marquand    8.400000
9     S.S. Rajamouli    8.400000

In [152]:
genres_split = movies['genres'].str.split('|')

movies['genre_1'] = genres_split.str[0]
movies['genre_2'] = genres_split.str[1].fillna(genres_split.str[0])

In [ ]:
PopGenre = (
    movies.groupby(['genre_1','genre_2'])['gross']
    .mean()
    .sort_values(ascending=False)
    .head(5)
    .reset_index()
)

PopGenre

In [ ]:
Meryl_Streep = movies[
    movies['actor_1_name'] == 'Meryl Streep'
]

Leo_Caprio = movies[
    movies['actor_1_name'] == 'Leonardo DiCaprio'
]

Brad_Pitt = movies[
    movies['actor_1_name'] == 'Brad Pitt'
]

In [ ]:
Combined = pd.concat(
    [Meryl_Streep, Leo_Caprio, Brad_Pitt],
    ignore_index=True
)

In [ ]:
actor_stats = (
    Combined.groupby('actor_1_name')
    [['num_critic_for_reviews',
      'num_user_for_reviews']]
    .mean()
)

print(actor_stats)

In [ ]:
critic_favorite = actor_stats['num_critic_for_reviews'].idxmax()

print("Critic Favorite Actor:", critic_favorite)

In [ ]:
audience_favorite = actor_stats['num_user_for_reviews'].idxmax()

print("Audience Favorite Actor:", audience_favorite)